services:
  testfrankenphp:
    build:
      context: .
    entrypoint: php artisan octane:frankenphp
    container_name: test-franken-app
    working_dir: /app
    volumes:
      - '.:/app'
    ports:
      - "8081:8000"
      - "80:80"
      - "443:443"
      - "5173:5173"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge